name: "Validate PR"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        ocaml_version: [4_11, 4_12]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: anmonteiro
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Build nix packages
        run: |
          nix-build ./sources.nix -A pkgs.ocaml-ng.ocamlPackages_${{ matrix.ocaml_version }}.piaf \
          -A pkgs.ocaml-ng.ocamlPackages_${{ matrix.ocaml_version }}.oidc \
          -A pkgs.ocaml-ng.ocamlPackages_${{ matrix.ocaml_version }}.tyxml-jsx
