name: "Validate PR"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        setup:
          - { ocaml-version: 4_11, continue-on-error: false }
          - { ocaml-version: 4_12, continue-on-error: false }
        config:
          - {os: "ubuntu-latest", target: "native"}
          - {os: "macos-latest", target: "native"}
          - {os: "ubuntu-latest", target: "arm64"}
          - {os: "ubuntu-latest", target: "musl"}
    name: Native packages (${{ matrix.config.os }}, OCaml ${{ matrix.setup.ocaml-version }})
    runs-on: ${{ matrix.config.os }}
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: anmonteiro
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Build nix packages
        run: |
          nix run -f ./sources.nix nix-build-uncached -c \
              nix-build-uncached ./ci.nix \
                --argstr ocamlVersion ${{ matrix.setup.ocaml-version }} \
                --argstr target ${{ matrix.config.target }} \
                --show-trace --keep-going
        continue-on-error: ${{ matrix.setup.continue-on-error }}

  cross-compilers:
    needs: [native]
    strategy:
      fail-fast: false
      matrix:
        ocaml-version:
          - 4_11
          - 4_12
        target:
          - arm64
          - musl
    name: ${{matrix.target}} packages (OCaml ${{ matrix.ocaml-version }})
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: anmonteiro
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Build nix packages
        run: |
          nix run -f ./sources.nix nix-build-uncached -c \
              nix-build-uncached ./ci.nix \
                --argstr ocamlVersion ${{ matrix.ocaml-version }} \
                --argstr target ${{ matrix.target }} \
                --show-trace --keep-going

  fmt:
    needs: [native, cross-compilers]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: fmt
        run: |
          find . -iname '*.nix' | xargs nix run -f ./sources.nix nixpkgs-fmt -c nixpkgs-fmt --check

